parameters :
    gco_exception_mapping.shortcuts:
            BadRequestHttpException: Symfony\Component\HttpKernel\Exception\BadRequestHttpException
            NotFoundHttpException: Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            ConflictHttpException: Symfony\Component\HttpKernel\Exception\ConflictHttpException
            AccessDeniedHttpException: Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
            FlattenHttpException: Symfony\Component\HttpKernel\Exception\FlattenException
            GoneHttpException: Symfony\Component\HttpKernel\Exception\GoneHttpException
            FatalErrorException: Symfony\Component\HttpKernel\Exception\FatalErrorException
            UnauthorizedHttpException: Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException
            LengthRequiredHttpException: Symfony\Component\HttpKernel\Exception\LengthRequiredHttpException
            MethodNotAllowedHttpException: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
            NotAcceptableHttpException: Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException
            PreconditionFailedHttpException: Symfony\Component\HttpKernel\Exception\PreconditionFailedHttpException
            PreconditionRequiredHttpException: Symfony\Component\HttpKernel\Exception\PreconditionRequiredHttpException
            UnprocessableEntityHttpException: Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException
            UnsupportedMediaTypeHttpException: Symfony\Component\HttpKernel\Exception\UnsupportedMediaTypeHttpException
            ServiceUnavailableHttpException: Symfony\Component\HttpKernel\Exception\ServiceUnavailableHttpException
            TooManyRequestsHttpException: Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException
            ##Adding a new exception ? Please respect the constructor interface used by all existing exceptions.
            ##Look at src/ExceptionTransformer/HttpExceptionTransformer.php::transform ($throw new $newException($exception->getMessage(), $exception);)
    gco_exception_mapping.exception_map:
            Doctrine\ORM\NoResultException: NotFoundHttpException