gco_get_user:
    path: /user/{id}
    defaults: {_controller: 'gco.user.controller:getUserAction'}
    methods: [GET]


gco_get_technology:
    path: /technology/{id}
    defaults: {_controller: 'gco.technology.controller:getTechnologyAction'}
    methods: [GET]
    requirements:
            id: '\d+'


gco_post_technology:
    path: /technology
    defaults: {_controller: 'gco.technology.controller:addTechnologyAction'}
    methods: [POST]