services:
    
    gco.userSkill.controller:
        class: 'GcoBundle\Controller\UserSkillController'
        arguments:
          - '@gco.userSkill.service'
          - '@gco.normalize'
          
    gco.userSkill.service:
        class: 'GcoBundle\Service\UserSkillService'
        arguments:
          - '@gco.userSkill.df'
             
    gco.user.df:
        class: 'GcoBundle\DataFixture\UserDataFixture'
        arguments:
          
    gco.userSkill.df:
        class: 'GcoBundle\DataFixture\UserSkillDataFixture'
        arguments:
          - '@doctrine'
                 
    gco.normalize:
        class: 'GcoBundle\Serializer\UserSkillSerializer'
        
    message.listener:
        class: GcoBundle\Listener\MessageExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            
    gco.exception_transformer.http_exception_transformer:
        class: GcoBundle\ExceptionTransformer\HttpExceptionTransformer
        arguments : [ '%gco_exception_mapping.shortcuts%' ]
        calls :
            - [ "addMap" , [ '%gco_exception_mapping.exception_map%' ] ]
            
    gco.exception_transformer.http_exception_listener:
        class: GcoBundle\Listener\ExceptionTransformerListener
        arguments: [ "@gco.exception_transformer.http_exception_transformer" ]
        tags:
            - { name: kernel.event_subscriber }
            
    gco.exception_transformer.rendering_listener:
        class: GcoBundle\Listener\MessageExceptionListener
        tags:
            - { name: kernel.event_subscriber }
