services:
    gco.user.controller:
        class: 'GcoBundle\Controller\UserController'
        arguments:
          - '@gco.user.df'
          - '@serializer'
#          - @gco.user.service
#    gco.user.service:
#        class: 'GcoBundle\Service\UserService'
#        arguments:
#          - gco.user.orm
    gco.user.df:
        class: 'GcoBundle\DataFixture\UserDataFixture'
        arguments:
          - '@doctrine'

    gco.technology.controller:
        class: 'GeoBundle\Controller\TechnologyController'
        arguments:
          - '@gco.technology.df'
          - '@serializer'