services:
    gco.user.controller:
        class: 'GcoBundle\Controller\UserController'
        arguments:
          - '@gco.user.df'
          - '@serializer'
#          - @gco.user.service
#    gco.user.service:
#        class: 'GcoBundle\Service\UserService'
#        arguments:
#          - gco.user.orm
    gco.user.df:
        class: 'GcoBundle\DataFixture\UserDataFixture'
        arguments:
          - '@doctrine'

    gco.core_technology.controller:
        class: 'GcoBundle\Controller\CoreTechnologyController'
        arguments:
            - '@gco.core_technology.service'
            - '@service_container'
            
    gco.core_technology.service:
        class: 'GcoBundle\Service\CoreTechnologyService'
        arguments:
            - '@gco.core_technology.data_fixture'
            - '@validator'
            
    gco.core_technology.data_fixture:
        class: 'GcoBundle\DataFixture\CoreTechnologyDataFixture'
        arguments:
            - '@doctrine.orm.entity_manager'

    message.listener:
        class: GcoBundle\Listener\MessageExceptionListener
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}