services:
    gco.user.controller:
        class: 'GcoBundle\Controller\UserController'
        arguments:
          - '@gco.user.df'
          - '@serializer'
#          - @gco.user.service
#    gco.user.service:
#        class: 'GcoBundle\Service\UserService'
#        arguments:
#          - gco.user.orm
    gco.user.df:
        class: 'GcoBundle\DataFixture\UserDataFixture'
        arguments:
          - '@doctrine'
    gco.list.technology:
            class: 'GcoBundle\DataFixture\TechnologyDataFixture'
            arguments:
              - '@doctrine'
    gco.technology.controller:
        class: 'GcoBundle\Controller\TechnologyController'
        arguments:
          - '@gco.technology.service'
          - '@serializer'
    gco.validator:
        class: 'GcoBundle\Validator\Validator'
    gco.technology.service:
        class: 'GcoBundle\Service\TechnologyService'
        arguments:
          - '@gco.list.technology'