services:
    gco.technology.technology_exists:
        class: 'GcoBundle\Validators\Constraints\TechnologyExistsValidator'
        arguments:
            - '@gco.skill.skill_service'
        tags:
            - { name: validator.constraint_validator }
            
    gco.core_technology.technology_exists:
        class: 'GcoBundle\Validators\Constraints\CoreTechnologyExistsValidator'
        arguments:
            - '@gco.core_technology.service'
        tags:
            - { name: validator.constraint_validator }