GcoBundle\Entity\Technology:
  constraints:
     - GcoBundle\Validators\ExistsCoreTechnology
     - GcoBundle\Validators\NoDuplicateTechnology

  properties:
    coreId:
      - Type: numeric

    technology:
      - Type: string
      - NotBlank: ~
