GcoBundle\Entity\Technology:
  constraints:
     - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [id]
        em: ''

  properties:
    coreId:
      - Type: integer

    technology:
      - Type: string
      - NotBlank: ~
