<?php

namespace GcoBundle\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function addLevel($name)
    {
        
        $em = $this->get;
        
        $level = new Level();
        $level->setName($name);
        
        $em->persist($level);
        $em->flush();
        
    }
    
}
