parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: gco
    database_user: root
    database_password: mclarenf1
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
