GcoBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        agency:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        roleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: role_id
    lifecycleCallbacks: {  }
